### ISSUE TITLE
Suggestions on how to group recipes

### ISSUE THREAD

**Issue by TomBT** [LukeSmithxyz/based.cooking#119]
I don't think we should adopt every single one of these, it's more or so a list of groups I could see making the recipes easier to find.
Region (Asian, European, Hispanic/Latin, etc.)
Nation (Italian, Chinese, Mexican, etc.)
Food Category (Poultry, Soups, Breads, Meats, Pastries, etc.)
Cooking Style (Boiled, Grilled, Baked, Steamed, etc.)
I'm not sure what these are called (Breakfast, Lunch, Dinner)
(Main Dish, Side Dish, snacks)
Difficulty/Accessability? (Easy, Medium, Hard)
^ to clarify, food like eggs, spaghetti, and chicken soup are much easier to make, obtain, and require less effort and equipment than say shrimp cocktails, pizza (from scratch), or Scandinavian Coffee Cake (self plug 😏).
I do see this one being the weakest of all the groups listed since the levels of difficulty are more blurred than say Food Category or Nation.

And of course feel free to add on.

**Comment by TomBT** [comment]
Oh I forgot one last one, by author.

**Comment by LukeSmithxyz** [comment]
Check out https://github.com/LukeSmithxyz/based.cooking/pull/78, I think I'll go with that or something like it.

**Comment by TomBT** [comment]
LOL, that was the one post I didn't read cause I thought it didn't deal with this topic. 😳
