### ISSUE TITLE
Add print functionality

### ISSUE THREAD

**Issue by jsmit42** [LukeSmithxyz/based.cooking#140]
My grandparents love finding new recipes online and this site is perfect for them because of their terrible internet connection. The only thing lacking for them here is an obvious print button (remember we are talking about **literal boomers** here, they don't realize they can simply press ctrl-p, nor do they realize they can copy and paste everything into a word document or something). An obvious print button would be quite beneficial for them and anyone else who may end up visiting based.cooking who does not enjoy watching Linux videos in their free time.

**Comment by DominikRusso** [comment]
That can't be done without js and I don't think luke wants any js in this project whatsoever.

**Comment by marekkowalczyk** [comment]
IMHO, bloat ;)

**Comment by LukeSmithxyz** [comment]
I would look into adding a "Print" button to their browser instead.
