### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by marekkowalczyk** [LukeSmithxyz/based.cooking#150]
Let's have a search box, in due time.

**Comment by Morelcia** [comment]
You can just use ctrl+f in browser.
I guess some simple php for searching could be useful if in the future categories on separate pages would be introduced.

**Comment by Goblin80** [comment]
#153

**Comment by Godje** [comment]
@Morelcia I assume the point is to not have a serverside preprocessor. Currently the side is literally assembled through a shell script. A search box with a JS filter function that has an array of pages would do just fine, and would be serverside. It simple enough and light enough to not need to be cached (which means we could just put it in the head of the script).

**Comment by Morelcia** [comment]
Afaik point is to be as lightweight as possible clientside and to work without js.
+serverside js abominations definitely aren't lightweight unless you meant something else.

**Comment by Godje** [comment]
@Morelcia definitely not serverside. Client side small amount of javascript (6 to 10 loc), inside the <head> `<script>` tag.

**Comment by Godje** [comment]
Since the amount of script I want to add is miniscule, it has no need to exist in a separate Network call to import the Javascript. So we can put it in the `<head>` tag, or at the bottom of HTML and forget it.
When you don't import the stuff in a separate file, it doesn't get cached. But since the amount of code is so small, there is no need for caching.

**Comment by Goblin80** [comment]
@Godje I see you point, and if you ask me i have no problem with minimal JS. but i don't think luke and the community will approve that. he was pretty clear about a no JS policy.

**Comment by marekkowalczyk** [comment]
How about just an alphabetized static index page of user-marked [[keywords]]?

**Comment by adeptflax** [comment]
How about JavaScript on the server-side? [http://www.cgi-node.org/](http://www.cgi-node.org/)

**Comment by Morelcia** [comment]
Why would someone run backend in language which runtime takes 500MB ram in idle? unironically php>nodejs

**Comment by adeptflax** [comment]
@Morelcia lol no it doesn't

**Comment by adeptflax** [comment]
ok serious this time, the more efficient thing would be a c++ nginx plugin.

**Comment by oussamabouchareb** [comment]
ctrl+f should be more than enough

**Comment by adeptflax** [comment]
the laziest way would probably be bash-cgi script.

**Comment by Dko1905** [comment]
> ctrl+f should be more than enough

The chad way to search is to use the inbuilt search.

**Comment by adeptflax** [comment]
actually making a duckduckgo search form would be even easier

**Comment by adeptflax** [comment]
```html
<form action="https://duckduckgo.com/">
  <input type="text" name="q">
  <input type="hidden" name="sites" value="based.cooking">
  <button type="submit">Search</button>
</form>
```

**Comment by adeptflax** [comment]
what you guys, think?

**Comment by vasilenko93** [comment]
Cannot see anything wrong with Ctrl-f, or / if you are using Vim keybindings. This might become a problem with thousands of recipes, maybe, but right now its not a problem at all.

**Comment by Godje** [comment]
@adeptflax I just tried what you did by just adding it in the devtools, and it genuinely works. This way we are not increasing the size of the website on the VPS, and we are increasing the search ratings for the based.cooking URL lol :)

**Comment by LukeSmithxyz** [comment]
Ctrl-f is more than sufficient now while all recipes are still on the main page.

If the site gets large enough, we will get a php search or something of the sort.
