### ISSUE TITLE
Alphabetical sort of recipes

### ISSUE THREAD

**Issue by skrzyp** [LukeSmithxyz/based.cooking#155]
You know it's not ordered properly right now.

I think it might be done by some Makefile rule or ssg modification instead of manually doing that. Some hipster frontend guy might probably come up with client-based sorting, but screw that.

Most likely related to: #153 #150 #20

**Comment by sylGauthier** [comment]
I implemented it in #78, for what it's worth. Result [here](sgauthier.fr/cooking).
