### ISSUE TITLE
Use the Schema/Recipe standard

### ISSUE THREAD

**Issue by AtomToast** [LukeSmithxyz/based.cooking#158]
I would suggest to create some template for new recipes that conforms to the [Schema/Recipe](https://www.schema.org/Recipe) standard. This is a widely used standard for recipe pages which makes it easily machine parseable. It is also what enables the recipe-scraper mentioned in #31 to work quite consistently on most popular pages.

Implementation wise, it's basically just some extra metadata added to the html tags. I would suggest having a look at the examples at the bottom of the page

**Comment by twiclo** [comment]
Is there an article that already follows this standard? I'd like an example to look to when converting my recipe

**Comment by AtomToast** [comment]
Most of the more bloated sites I know use some script tag together json data in order to generate the html. For a simpler application I would suggest just looking at the examples at the bottom of the schema.org page linked above

**Comment by twiclo** [comment]
Oh so this is something that the SSG needs to implement? I can't just put these things in my markdown?

**Comment by AtomToast** [comment]
It's not something that markdown supports, it's too simple for that. The tags need to be placed inside of the respective html tags

**Comment by DGKSK8LIFE** [comment]
> It's not something that markdown supports, it's too simple for that. The tags need to be placed inside of the respective html tags


Markdown on the web (most of the time), encodes/renders in HTML. Markdown engines like the one Github uses supports HTML and CSS tags. FYI.

**Comment by AtomToast** [comment]
But wouldn't that kind of ruin the point of using markdown in the first place?

Could you give me a mockup of what such an html embed might look like in this case?

**Comment by DGKSK8LIFE** [comment]
> But wouldn't that kind of ruin the point of using markdown in the first place?

It complements markdown, giving it features that it doesn't have by default; but shouldn't be overused.

> Could you give me a mockup of what such an html embed might look like in this case?

Yeah here's an example from my profile README:

```md
# Hi there <img src="https://media.giphy.com/media/gM5qFksULw54NMWyry/giphy.gif" height="50"/>, I'm Tarek Ali - aka DGK 
```

**Comment by AtomToast** [comment]
Hm, given that one of markdowns main purposes was to be human readable I am still not the biggest fan of this but for usecases like these it should still be okay. It should probably be quite simple to have a static site generator embed some inline html tags

**Comment by twiclo** [comment]
So it sounds like I can use these tags right now to get my recipe up to the standard?

**Comment by AtomToast** [comment]
Not entirely sure how the generator works at the moment but I would assume that it would actually need to be added on it's end

**Comment by DGKSK8LIFE** [comment]
> Not entirely sure how the generator works at the moment but I would assume that it would actually need to be added on it's end

It's not an SSG, it's native HTML rendering support by the markdown engine (using the HTML tags in this case, not markdown)

**Comment by twiclo** [comment]
So that's a... yes?

**Comment by AtomToast** [comment]
> It's not an SSG, it's native HTML rendering support by the markdown engine (using the HTML tags in this case, not markdown)

I am not really sure what you are talking about here. The software luke uses clearly defines itself as "a small static blog generator" https://pedantic.software/git/blogit/about/

I would suspect that with the current setup it would require some extra work to get this setup working since people don't write their recipes in just plain html

**Comment by DGKSK8LIFE** [comment]
> I would suspect that with the current setup it would require some extra work to get this setup working since people don't write their recipes in just plain html

Yeah, I was talking about markdown rendering on the web in general, not sure about this particular SSG.

**Comment by solonovamax** [comment]
Why is this closed as completed?

This has not been implemented on the website what-so-ever.

I would personally find this feature very useful, as [Nextcloud Cookbook](https://apps.nextcloud.com/apps/cookbook) allows me to automatically import recipes from websites that conform to the Schema/Recipe standard.
