### ISSUE TITLE
Yogurt requires yogurt?

### ISSUE THREAD

**Issue by Ashdemai** [LukeSmithxyz/based.cooking#159]
Is it only me, but the recipe for Yogurt asks for [yogurt](https://github.com/LukeSmithxyz/based.cooking/blame/master/src/yogurt.md#L8) as an ingredient? Something doesn't add up, why would I create something if I need it in the first place to create it.

**Comment by owwk** [comment]
I believe it's because you need all the bacteria etc. from existing yoghurt. This recipe is perhaps better thought of as a way to multiply yoghurt.

**Comment by LukeSmithxyz** [comment]
Lol yeah that's how it works. Specifically, you need the bacterial cultures in already existing yogurt to make more.
