### ISSUE TITLE
Make recipes machine readable

### ISSUE THREAD

**Issue by DarkWiiPlayer** [LukeSmithxyz/based.cooking#170]
It'd be nice if measurements and ingredients would be wrapped in `<data>` tags to make them more machine-readable.

What for?
- Automatically convert measurement units
- Adding custom styles for these elements (like making them bold)
- Wrapping ingredients in links to an amazon search, or the wikipedia page, or whatever.
- Extract the data to automatically feed it into whatever other app.

Or whatever else people might want to do with this data. My point is that it should be available somehow.

The way I would suggest doing this is:

```html
Add <data class="measurement" data="30 g">a fuckton</data>
of <data class="ingredient" data="Himalayan Salt">Salt</data>.
```

**Comment by DominikRusso** [comment]
I have a feeling submitters will get this wrong more often than not (missing tags, incorrect class, wrong or inconsistent unit of measurement, etc.). 

This would also mess up the human-readable markdown. So then we'd need to store a proper human-readable markdown version of each recipe for the curl interface (or for just viewing the recipes locally in plaintext) and another version with the tags. Sure, removing the tags could be automated but I'd say this _feature_ has more downsides than benefits.

> Wrapping ingredients in links to an amazon search

Nice try, Jeff.
