### ISSUE TITLE
Generate PDF/Latex recipe book

### ISSUE THREAD

**Issue by sylGauthier** [LukeSmithxyz/based.cooking#184]
Generate Latex files and pdf with link to download it from the index, to have it in a nice printable format or just read it offline.

`pandoc` can do the job pretty well apparently.

I would even be down for groff versions as well, to read the recipes from the terminal.

**Comment by LukeSmithxyz** [comment]
I don't really see what advantage this would give over one's browser's built-in print feature.

**Comment by sylGauthier** [comment]
> I don't really see what advantage this would give over one's browser's built-in print feature.

Better presentation, possibility of leaving an empty form at the bottom for boomers to write down tips with their boomer pen, and some autists like myself don't necessarily have a bloated browser with a print option.

And the more I think about it, the more I like the idea of man-page style recipes that I can just browse on my terminal with a simple
```
curl <recipe> | groff -man
```

I'll implement it quickly on my fork once I'm done wage-slaving for the day and you see if you like it.

**Comment by jsmit42** [comment]
I proposed adding a print feature a few days ago and Luke and others changed my mind about it, its really not necessary. If you want to view things offline just use `curl` or `wget` or the stuff you want and view the HTML in your browser or convert that to a PDF yourself if you want to. 

> > I don't really see what advantage this would give over one's browser's built-in print feature.
> 
> Better presentation, possibility of leaving an empty form at the bottom for boomers to write down tips with their boomer pen, and some autists like myself don't necessarily have a bloated browser with a print option.
> 
> And the more I think about it, the more I like the idea of man-page style recipes that I can just browse on my terminal with a simple
> 
> ```
> curl <recipe> | groff -man
> ```
> 
> I'll implement it quickly on my fork once I'm done wage-slaving for the day and you see if you like it.

I proposed adding a print feature a few days ago and Luke and others changed my mind about it, it's really not necessary. If you want to view things offline just use `curl` or `wget` or the stuff you want (or do `wget -r` and pull the whole site down) and view the HTML in your browser or convert it to a PDF yourself if you want to. Adding something to the site for everyone to do that would simply be bloat.

And as for boomers and their boomer pen, real boomers have no concept of white-space. My grandma has cookbooks from the 50s with four columns of text and absolutely no margins and she still finds space to write notes if she wants to.

**Comment by twiclo** [comment]
I thought it'd be interesting to auto generate index card sized recipes. My fiance prefers to have recipes written down in her recipe box so this way I could easily print those out

**Comment by LukeSmithxyz** [comment]
Well, these are interesting ideas, but I don't want them to be built into the site. Sort of defeats the purpose.

I think it might be okay if we later include a list of tips and hacks to do things like this to site content on the command line, but again, I think the print page suffices. If you want it to look nicer, you can change the print output CSS.

**Comment by twiclo** [comment]
Okay so what can I look into to if I want to format these to a flashcard format?
