### ISSUE TITLE
Opengraph meta tags

### ISSUE THREAD

**Issue by anon-temper-sama** [LukeSmithxyz/based.cooking#190]
For the sake of linking this on more botnet sites it would help if `templates/header.html` had some opengraph meta tags for clean looking embeds.

I think most sites use this to generate fancy embedded links so these should be all the tags we would need

```
<meta property="og:title" content="Based Cooking">
<meta property="og:site_name" content="Based Cooking">
<meta property="og:url" content="based.cooking">
<meta property="og:description" content="Only Based cooking. No ads, no tracking, nothing but based cooking.">
<meta property="og:type" content="article">
<meta property="og:image" content="">
```

The `og:image` on just needs a full link to an image so no URI's (`/path/to/image.png`). I usually just use the project logo from my Gitlab repos to not put any undue load on the server.

Reference to available opengraph tags: https://ogp.me/

**Comment by LukeSmithxyz** [comment]
Okay. I guess the content in `description` should be whatever description of the recipe there is above the ingredients list. This could be doable.
