### ISSUE TITLE
Clicking on recipe shrinks on Android Device

### ISSUE THREAD

**Issue by sysgrammer** [LukeSmithxyz/based.cooking#222]
Expected Behaviour: Open based.cooking, Find the recipe to open, click on it, recipe page appears, cook it.

Bug: Upon clicking the link/name of the recipe, the recipe hyperlink shrinks instead of opening the webpage. Then a reclick on the same link/name is required to open the webpage.

Tested on: 
Device- Poco F1
Browser- Brave
Android Version- Android 11

**Comment by jesperbakhandskemager** [comment]
I tested on both Brave and Bromite, i get the same error too

**Comment by taco-c** [comment]
My pull request might have fixed this issue, please try again now.

**Comment by sysgrammer** [comment]
Yes it is fixed now. Thank You
