### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by cuberobenicio32** [LukeSmithxyz/based.cooking#224]
Hi. I was wondering, can people commit recipes in another language (spanish, for example) ? I know that it would be probably require more maintenance by people that are native in that language, but I guess we could do that, we have a pretty big community interested in this project. We could sort the recipes in another languages by tags or just by adding a whole new directory (the last option would be the ideal).
Thanks.

**Comment by pniedzwiedzinski** [comment]
#82

**Comment by cuberobenicio32** [comment]
Ok, I have taked a look into the issue, thank you for pointing it to me. Closing this, I will try to make a fork of this website on spanish :).
