### ISSUE TITLE
Macronutrients

### ISSUE THREAD

**Issue by LouisDeconinck** [LukeSmithxyz/based.cooking#234]
Add the macronutrients for every dish/ingredient.

**Comment by jsmit42** [comment]
That's a bit much to ask of the volunteers who write recipes here. I've written a few, I plan to write more, but if there was such a requirement I would not write any more, that sounds like too much work.

**Comment by pahlse** [comment]
Yes. Thats my opinion too. I wouldn't know how to consequently find such information for specific ingredients

**Comment by DominikRusso** [comment]
Tracking nutrients is unsustainable. What are the macronutrients of "thinly sliced meat"?

**Comment by Saga-** [comment]
It doesn't have to be exact, it could just be an estimate (and nor should it be required)
For most of it, it is only a matter of searching 'how many calories in Xg' for each ingredient listed

**Comment by LukeSmithxyz** [comment]
Way too much work and is too autistic and non-based.

**Comment by lodenrogue** [comment]
> too autistic 

That's inappropriate and disrespectful
