### ISSUE TITLE
separate recipes from website internals into a different repo

### ISSUE THREAD

**Issue by sylGauthier** [LukeSmithxyz/based.cooking#249]
People keep coming up with different formatting/content distribution/search system ideas.

Why not simply offer a simple repo of markdown recipes and put all the site-generation tools in a separate repo?

This would allow to integrate the recipes into whatever system they like the most, while keeping the actual valuable data centralised in a single repository.

It would also make it easier to give some people some commit rights to the recipe repository to improve the flow.

**Comment by Dko1905** [comment]
If this is going to happen I would recommend git subtrees, they are better than submodules for multiple reasons, [here is some more info about them](https://www.atlassian.com/git/tutorials/git-subtree).

**Comment by sylGauthier** [comment]
I think I'm done with this repository. I'll maintain my own [hard fork](https://github.com/sylGauthier/recipes) for my personal use and will try my best to keep it in sync with this one. It will differ from this repository by:

- not having any code to display recipes/build website, for proper separation of code and data.
- having stricter rules on formatting and writing style, in particular, no donation link, no personal stories, 0 tolerance for spelling mistakes.
- having a script to assist writing recipes by letting the user enter all content semantically then generating a properly formatted markdown file.
- no support for images.

I've rewritten all recipes to remove all useless personal blog stories and use of the pronoun "I", "My" etc, removed all donation links which don't belong in a recipe. I kept authors' names and websites but that's it.

I'm making a [man page](https://github.com/sylGauthier/cook) system as well to work with it, because I like reading recipes on the terminal and the `man` macro package fits perfectly the style, plus `groff` can export it into any format in existence.

**Comment by Dko1905** [comment]
> No support for images.
I would argue images are very useful, and aren't bloat.
