### ISSUE TITLE
Move to self hosted GitHub alternative

### ISSUE THREAD

**Issue by Dko1905** [LukeSmithxyz/based.cooking#266]
Some people don't like using a centralized website, that has the power to take down any repo for any reason. Therefore I suggest that this repo should be moved to self hosted alternative, Gitea is good but it requires a lot of setup and is still quite bloated, we could also do what [suckless](https://suckless.org/) do.

**Comment by kiprasmel** [comment]
I mean luke perhaps could mirror this on gitlab, or on his own site (gitlab is oss and available for self-hosting too), but there's a tradeoff of being "decentralized" and being useful, and I don't think a cooking recipe website is at risk (if it were - we'd have way more problems to worry about lol)

**Comment by LukeSmithxyz** [comment]
I already have a Gitea server, but it doesn't really have the administrative capabilities to do many things. I'm not using Gitlab for sure, which sucks (there is a mirror on my Gitlab right now, but who cares).

I'll be more likely to move to Sourcehut or an actually good place when I get absolutely sick of being inundated with PRs here (getting close tbh).

**Comment by Dko1905** [comment]
I have heard a lot of good things about Sourcehut, but the UI is not very intuitive.

**Comment by Morelcia** [comment]
I think that interest would die if pr/issues etc would get moved away from github as it's most popular platform. Just mirrors are enough I guess. 
Also if you can't handle retards not following templates then maybe getting another maintainer with rights to merging would be good solution?

**Comment by Dko1905** [comment]
You're probably right that some of the interest would go away if we switched away from Github, but groups like suckless still survive without Github. I think it's more relevant now because Microsoft owns GitHub.
More people with merge permissions would also help with the current amount of prs, but I think it's just a spike right now.

**Comment by wesleydeal** [comment]
Though certainly possible, I find it hard to believe that GitHub would be interested in terminating a simple repository of recipes, regardless of how many articles The Guardian writes about Luke.

**Comment by Knarkzel** [comment]
It's very easy to host via sourcehut as well, using https://srht.site. Also based to use email > github frontend.

**Comment by the3dfxdude** [comment]
There is no reason to use any of these centralized git sites for submissions or its collaboration features. People trafficking the based.cooking site for recipes is the best way to generate interest in submissions. So there can be a link to a page explaining there what to do and the submission could be a form, or a designated email address. No one needs to know there is git managing it underneath.

The only good git sites are for something like this is for mirroring the data. Even that is not really needed.

**Comment by Dko1905** [comment]
> So there can be a link to a page explaining there what to do and the submission could be a form, or a designated email address.

@the3dfxdude As I understand, you want a form or email for creating recipes, if so this is against one of the reasons this project was created.
Luke Smith specifically created this site to create, edit and share recipes using git, because git is cool.

**Comment by the3dfxdude** [comment]
> > So there can be a link to a page explaining there what to do and the submission could be a form, or a designated email address.
> 
> @the3dfxdude As I understand, you want a form or email for creating recipes, if so this is against one of the reasons this project was created.
> Luke Smith specifically created this site to create, edit and share recipes using git, because git is cool.

I was speaking about places like github being unnecessary to manage collaboration. git can still be used to track changes. So whatever form that can take will work.

I thought sharing recipes was supposed to be through visiting the website.

**Comment by Dko1905** [comment]
> git can still be used to track changes. So whatever form that can take will work.

Yes git can be controller through a web interface, but this messes up the metadata of the committers, e.g. I could no longer sign my commits with my GPG key. I also personally think it's better doing this through git, GitHub or not.

> I thought sharing recipes was supposed to be through visiting the website.

Viewing the recipes is through the web page, but creating & editing is through git.

You may be interested in #466, it proposes a script for recipe creation.

**Comment by the3dfxdude** [comment]
It's great that you know git and know how to use GPG keys to sign your commits. I'm not suggesting anything to prevent that as it happens now, or even really talking about ways to use git. I'm talking about collaboration. Collaboration should begin from the traffic through the website. If you want the most resilient site that does not primarily rely on collaborating through a github style webpage, or even that git is involved, and attract the kinds of people looking to exchange recipes, then the steps should be normie friendly enough. The audience could increase considerably with some simple additions.

I showed the website to others, and they thought it was cool it wasn't filled with ads costing only pennies and could be made with everyone's help. But if I start talking about git and how that made the website, then you'll get a you're a crazy talking about nothing I care about look.

**Comment by Yaroslav-95** [comment]
> I'll be more likely to move to Sourcehut or an actually good place when I get absolutely sick of being inundated with PRs here (getting close tbh).

I say that is a good decision, especially if you decide to adopt the decentralized email-based git worflow instead of the centralized Github PR worflow. That way there wouldn't be any need for people that are not registered on Github or any other git-hosting service to submit their recipes.

**Comment by Dko1905** [comment]
> I say that is a good decision, especially if you decide to adopt the decentralized email-based git worflow instead of the centralized Github PR worflow. That way there wouldn't be any need for people that are not registered on Github or any other git-hosting service to submit their recipes.


**b a s e d !**
