### ISSUE TITLE
My argument in favor of "regulated javascript"

### ISSUE THREAD

**Issue by marttoygoy4** [LukeSmithxyz/based.cooking#269]
Hey luke I am a long time subscriber, I am all on with the against with the so call "modern web" that get us backwords in technology and computing

We need Soyfied.JS lol this project really gives me vibes of OH SHIT THIS IS THE FUTURE
honestly I would like a JS slide bar that could resize the text 
![image](https://user-images.githubusercontent.com/80398595/111875688-bdaf7800-89a3-11eb-89a5-897fcb2a9635.png)
![image](https://user-images.githubusercontent.com/80398595/111875706-cc962a80-89a3-11eb-9b4c-9da897ce5fe6.png)

when they make javascript bloated its bad I dont think javascript should be used that way, they are many parts I HATE about javascript I think the main idea of javascript where it let you add and costomize your thing is "where its at" not 1mb of fucking javascript lol

also check out this javascript 
![image](https://user-images.githubusercontent.com/80398595/111875749-0c5d1200-89a4-11eb-9c5f-d2bd602be49d.png)
This is how I think javascript should be used no otherway

What happen to websites that let you customize your mouse and shit, every website used to have its own thing nowdays its all about huge buttons flat icons that doesnt even represent their meaning  highly cpu intrusive javascript code that doesnt even make sense.... **I miss the old internet where many people had their websites**, and **mega-linking to other websites** and those cool and neet things that every **website had** but now we dont have it. Shame how we are lacking creativety in nowdays websites and we just will never have the avarage joes making a website and when they do its all bloated with this "over somplfing" shit that really just make things harder, I see my self as kindda tech savy? I guess but I never felt so off hand in computing when I see a modern website, so bloated and I loose my mind of how people like it.

Love your channel luke :)

**Comment by candreslobor** [comment]
I think that the whole purpose of this is a non-javascript website regardless JavaScript could be used is a more optimal way

**Comment by marttoygoy4** [comment]
> I think that the whole purpose of this is a non-javascript website regardless JavaScript could be used is a more optimal way

Yeah I do like those HTML only websites but aint we alll miss those websites that had their own thing, wether its a mouse-icon-changer or a join counter and stats of which counties people visited the www-site. uhhhh I miss the 1990;s I am not being a boomer and wanna say IN MY AGE WE HAD THIS AND THIS but its really the case either a boomer or not it really was better in the 90's

**Comment by marttoygoy4** [comment]
> I think that the whole purpose of this is a non-javascript website regardless JavaScript could be used is a more optimal way

Im also for GUI's, the welcoming feeling of each program is something I truly enjoy from computing shame we dont have it today in today programs and those that do(aka naintained), are from the 90s/2002-2012 lets be honest here

**Comment by marttoygoy4** [comment]
> I think that the whole purpose of this is a non-javascript website regardless JavaScript could be used is a more optimal way

![image](https://user-images.githubusercontent.com/80398595/111876522-cace6600-89a7-11eb-8ca2-d598d06c4931.png)
