### ISSUE TITLE
add option to toggle dark theme

### ISSUE THREAD

**Issue by lmssieh** [LukeSmithxyz/based.cooking#283]
here is an example that works without js.

https://codepen.io/oahehc/pen/OJPjZXB

**Comment by adeptflax** [comment]
neat

**Comment by marttoygoy4** [comment]
> ![image](https://user-images.githubusercontent.com/80398595/111880002-965fa780-89b1-11eb-9580-e31eeed4f74a.png)
> I know the argument against javascript I hate HTML5 too, but I made a javascript/userscript plugin to add this pull :)
> no bs, just niceness :)
> 
> ```js
> // ==UserScript==
> // @name        New script - based.cooking
> // @namespace   Violentmonkey Scripts
> // @match       https://based.cooking/
> // @grant       none
> // @version     1.0
> // @author      -
> // @description 3/20/2021, 7:09:37 PM
> // @run-at   document-start
> // ==/UserScript==
> 
> ////// CUSTOM 90's JS fun :) 
> //Why Javascript could be based too
> document.querySelector("body > div > h1").textContent = "--> BasedN'Redpilled, no BS! ;) <--"; //I got this querySelector value -> // -> https://i.imgur.com/IUq4NXZ.png
> //document.documentElement.style.cursor="wait";//Old school :) just have the wait cursor until you hover the thing :) I use it, I suggest you to try it
> 
> ////////////////////
> function GM_addStyle (cssStr) {
>     var D               = document;
>     var newNode         = D.createElement ('style');
>     newNode.textContent = cssStr;
> 
>     var targ    = D.getElementsByTagName ('head')[0] || D.body || D.documentElement;
>     targ.appendChild (newNode);
> }
> 
> GM_addStyle ( `
> 	body {
> 		background: #F2F4F3 ;
> 		color: #1F1E1F ;
> 	}
> 	a {
> 		color: tomato ;
> 	}
> 	a:visited {
> 		color: gray ;
>   }
> `);
> ```

Please check https://github.com/LukeSmithxyz/based.cooking/pull/261#issuecomment-803429684
I made a whole userscript for counter this javascript need issue :) dont take me wrong I think its really cool to have this HTML sites again1!!!

**Comment by Goblin80** [comment]
#212

**Comment by LukeSmithxyz** [comment]
There is already a dark mode. In fact, it is default unless you have set your browser to want a light theme.

**Comment by kskeigrshi** [comment]
Chromium with the dark GTK theme in Linux and FreeBSD shows up as light. Is there any way to fix this?
