### ISSUE TITLE
Suggestion: change the ** **  to <b></b>

### ISSUE THREAD

**Issue by marttoygoy4** [LukeSmithxyz/based.cooking#293]
Hey luke/Hey Community,

big fan of the project, please consider changing the ** markdown thing to <b> html-statement.
Thanks!

**Comment by notthewave** [comment]
Why?

**Comment by marttoygoy4** [comment]
> Why?

Why not have a bold theme-ish thing?

**Comment by DominikRusso** [comment]
`**text**` already becomes `<strong>text</strong>`.

**Comment by sylGauthier** [comment]
The literal point of markdown is to make our life slightly less miserable by not writing HTML, as well as the possibility to compile it to different formats like man pages.

Putting HTML in a markdown file is like putting an `asm()` directive in C code, or soy milk in your coffee. We simply don't do it here.

**Comment by marttoygoy4** [comment]
> The literal point of markdown is to make our life slightly less miserable by not writing HTML, as well as the possibility to compile it to different formats like man pages.
> 
> Putting HTML in a markdown file is like putting an `asm()` directive in C code, or soy milk in your coffee. We simply don't do it here.

The only reason you would want to compile a man page is when you have many many formats, docs. html-docs and etc. Writing a man page shouldnt be an issue every once in a while when there is a new future.
>soy in your coffee 
>haha I am better than you 
>linar thinking like you are in a cult 
This shame lack of creativety is why the modern web is so bloat, so do me a favor have some **critical thinking**, and have some creativity. But actually I am not sure about 
>Its liking using asm() in your C code
while in many cases it wouldnt make sense sometimes it would make in rare edge cases where you might want to optimise a certain issue with your compiler? regarding our case I really dont think its the same thing and that we can compare that to our case because its literally changing something you woul;d write in X language lets say you use python and you write your line which is "xValue = 'string' " and then you regex and replace it to look like something you would see in a C code lets say ? its the same thing I think think your argument is too strong, I disagree but I guess this is just my opnion not here to attack last time I touched code was in a SVN in 2008 and that was a helping an opengl demo for a friend written in C.

>to different formats like man pages. 
why not regexing it("") and literally replacing it with <b> </b> do we have an issue regexing between two different strings and put html tags between the two?
![image](https://user-images.githubusercontent.com/80398595/111910394-da15e800-8a69-11eb-9c3b-34849913ec1d.png)

How is this an hassle?
Literally all you need to do is A , find all test between ** ** and then put the HTML tags around the regex text once that done remove all the * from the text and you should have it  

Maybe I am missing here something and I sound like a complete idiot but I dont understand where is the issue here?

**Comment by DominikRusso** [comment]
The recipes are written in markdown and markdown syntax for bold text is `**text you want emboldened**`.
The site generator then converts the markdown syntax to HTML, in which the syntax for bold text is `<strong>text you want emboldened</strong>`.

I'm not quite sure what the issue here is.

**Comment by marttoygoy4** [comment]
> The recipes are written in markdown and markdown syntax for bold text is `**text you want emboldened**`.
> The site generator then converts the markdown syntax to HTML, in which the syntax for bold text is `<strong>text you want emboldened</strong>`.
> 
> I'm not quite sure what the issue here is.

oh im retarded oops
