### ISSUE TITLE
Suggestion: Add Vegetarian/Vegan to basic tags

### ISSUE THREAD

**Issue by phil330d** [LukeSmithxyz/based.cooking#306]
Not sure if there are any other relevant ones but there are a lot of recipes which are vegetarian/vegan right now, and it would be nice to filter for them.

**Comment by longdas** [comment]
![image](https://user-images.githubusercontent.com/57007241/111884680-98b60780-8999-11eb-9e95-e85c09128a7e.png)

this you?

**Comment by phil330d** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/57007241/111884680-98b60780-8999-11eb-9e95-e85c09128a7e.png)
> 
> this you?

No it's not. It's a fact that there are a lot of recipes without meat on the site (Broccoli, Hummus, Pasta Sauce, Ketchup etc.). Idc about veganism and such, but sometimes you want something without meat (which there is on the site), and it wouldn't be that difficult. But if you guys insist on not adding it, fine, so be it.

**Comment by Jackojc** [comment]
Wondering if it might be good to reopen this issue. Even if you don't necessarily agree with the ideology of Veganism, the advantages include cost (meat is always more expensive at least where I live), independence (easy to grow plants) and (potentially) better health.
