### ISSUE TITLE
Automatically convert SI/Imperial units

### ISSUE THREAD

**Issue by gordon-quad** [LukeSmithxyz/based.cooking#311]
Somewhat related to #170 and #158.

Would be great to define the format of how units are specified and have simple pre-processor that does the conversion before publishing.
It is already in half of the recipes but people just specify it by hand, so why not automate it?

**Comment by DLComDev** [comment]
Hahaha, I was just about to make this exact request. Yes, please! It's super annoying to manually convert all the time, especially when you are mixing multiple recipes from people with different units of measurement.

**Comment by Goblin80** [comment]
#143
