### ISSUE TITLE
Add tags based on dietary restrictions

### ISSUE THREAD

**Issue by JimmyCushnie** [LukeSmithxyz/based.cooking#317]
Hi,

This is exactly the kind of cooking website I'm looking for, but as someone who doesn't eat meat it's a bit cumbersome to sort through the recipes looking for the meat-free dishes. There's already a tags system, so I think tags should be added for common dietary restrictions. That way, folks with particular diets can easily find the foods that fit their diet.

Here are my suggestions for dietary restriction tags:

- Vegetarian
- Vegan
- Nut-free
- Gluten free
- Kosher
- Halal

Thanks for making a great website!

**Comment by MFG080xc0** [comment]
lmao

**Comment by Morelcia** [comment]
vegan mega cringe but nut/gluten-free would be actually useful for people that have allergy

**Comment by MFG080xc0** [comment]
> vegan mega cringe but nut/gluten-free would be actually useful for people that have allergy

based (.cooking)

**Comment by jsmit42** [comment]
You realize this is an open source project, right? If you want something like that to happen it is best to do it yourself and open a pull request with those tags added. You can't guarantee that anyone is going to do this for you.
