### ISSUE TITLE
Consider hosting the repo on sourcehut.org instead of GitHub

### ISSUE THREAD

**Issue by mfru** [LukeSmithxyz/based.cooking#334]
https://sourcehut.org/

Pros:
- No bloat
- Open source

Cons:
- in alpha

**Comment by marttoygoy4** [comment]
Eh I dont think github is too bloated, I actually like it I wish they had a more 3d-like style

**Comment by m-chrzan** [comment]
The biggest benefit of GitHub is that it's popular and easy to use. Which are of course not benefits in and of themselves, but they are useful when you  want to use it as a submission mechanism.

**Comment by LukeSmithxyz** [comment]
dup of #266
