### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by kevin-b-lockwood** [LukeSmithxyz/based.cooking#35]
I'm thinking it might be good to have a feed to notify that a new recipe has been added. Not necessarily a really important addition, but if it's not too much work it would be a nice-to-have.

**Comment by LukeSmithxyz** [comment]
Yeah I've thought about it, but I don't want to add it now just because
I figure it might end up with like a bajillion entries a day. As new
stuff starts to be added slower, I'll work a system out.

**Comment by ile6695** [comment]
You can get commits as a feed [https://github.com/LukeSmithxyz/based.cooking/commits.atom](https://github.com/LukeSmithxyz/based.cooking/commits.atom)

**Comment by kevin-b-lockwood** [comment]
Sounds good! This is an awesome resource, I can see myself using it a lot as it develops and grows.

**Comment by LukeSmithxyz** [comment]
> You can get commits as a feed https://github.com/LukeSmithxyz/based.cooking/commits.atom

Well, that's going to give people a lot of trash, spelling changes and no content consoomable in an RSS feed reader (it only contains commit messages.

Ideally the text of new articles should be included in entirely in an RSS feed entry so people can see new things from their RSS readers.

**Comment by kocotian** [comment]
Maybe script that would get all recipes, sort them by modification date, `head`ing last, let's say, 25 recipes, and making some rss from this?

**Comment by marekkowalczyk** [comment]
How about [https://rgz.ee/rssg.html](https://rgz.ee/rssg.html)?

**Comment by sylGauthier** [comment]
It's also implemented in #78 as a simple Makefile rule.
