### ISSUE TITLE
Tag system bug

### ISSUE THREAD

**Issue by throwaway1037** [LukeSmithxyz/based.cooking#354]
Some recipes are repeated twice when you visit a particular tag.

Eg. [the cake tag](https://based.cooking/@cake).

**Comment by hallzy** [comment]
Interesting. I wonder if at least in the case of the `cake` tag that it is because it uses the `pancake` tag also as a `cake` tag.

Something that the duplicates have in common for that tag are that they are tagged as both `pancake` and as `cake`.

**Comment by throwaway1037** [comment]
I hate to say it, but there are still duplicates.

**Comment by hallzy** [comment]
@throwaway1037 It doesn't look like the PR is actually live yet. I check a recipe change before and after this, and neither recipe is changed on the site either, so I am going to assume that that is the reason for now.

**Comment by throwaway1037** [comment]
It's fixed,

**Comment by hallzy** [comment]
@throwaway1037 ah I was trying to find this issue so I could reference it

I noticed that the CI was broken #413 and that has been fixed now, so that's why nothing was updating.
