### ISSUE TITLE
Consider using Vercel

### ISSUE THREAD

**Issue by Ambyjkl** [LukeSmithxyz/based.cooking#356]
https://vercel.app is a great service for free unlimited static hosting, complete with automatic CDN, making it both faster and cheaper (free) than a VPS.

Here an example: https://based-cooking-ambyjkl.vercel.app/

(styling is currently broken because for some reason the css file doesn't make it into the html files, I'd appreciate someone helping me with that)

**Comment by zyansheep** [comment]
You could also host it on ipfs to make it truly decentralized

**Comment by Ambyjkl** [comment]
@LukeSmithxyz is this a wontfix then?
