### ISSUE TITLE
Fixing the mix of messurments.

### ISSUE THREAD

**Issue by chakeson** [LukeSmithxyz/based.cooking#364]
Half the recipes are using European cups and some are using UK cups and some are using American cooking measurements. Maybe have it detect your IP and display appropriate measurements for your region and then allow you to choose if the automatic choice was not useful.

**Comment by SleepingCrows** [comment]
Or just move the ingredients into a markdown table, and provide the 3 most common units of measurements, since what you're asking probably can only be done with JS.

**Comment by taco-c** [comment]
#143
