### ISSUE TITLE
What is the fencedcode directory that the makefile references?

### ISSUE THREAD

**Issue by zyansheep** [LukeSmithxyz/based.cooking#366]
I'm trying to build the website and host it on ipfs but the index.html doesn't build with the correct header or css. I think there must be some hidden folder on the vcs that the makefile uses. Is there any way I can get this folder so that the website builds correctly?
Makefile error:
`fencedcode: No such file or directory`
Edit: figured out why it wasn't building with the correct css (the `make tags` command was messing stuff up), but I am still curious what the fencedcode directory is.

**Comment by taco-c** [comment]
It is an option to the `markdown` program that according to the man page "Allow[s] fenced code blocks".

This repository is using the package `discount` for the markdown-to-HTML translation. Make sure you have it installed.
