### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by PrWalterB** [LukeSmithxyz/based.cooking#389]
An option to somehow made translation to other languages should be add.

**Comment by teunissenstefan** [comment]
#82

**Comment by lisbonjoker** [comment]
I would be willing to maintain the Portuguese fork. If @LukeSmithxyz would like to use the subdomain option like people have refered. pt.based.cooking for example.

**Comment by PrWalterB** [comment]
> I would be willing to maintain the Portuguese branch. If @LukeSmithxyz would like to use the subdomain option like people have refered. pt.based.cooking for example.

Personnally, I would be willing to maintain a French branch.
