### ISSUE TITLE
USEFUL: Program for checking whether a markdown file follow rules for submission

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/based.cooking#401]
`based` is a simple tool I created today that both checks for whether the content of a markdown file contain everything it needs from [the rules](https://github.com/LukeSmithxyz/based.cooking#rules-for-submission). It also formats the file so it doesn't look ugly.

It checks for the following:

- Bad filename (spaces, missing extension, uppercase letters)
- Missing prep time / cook time / servings (as well as emoji variant, a bunch of people delete this for some reason)
- Salt (pepper is too generic)
- No image

If the file have no errors, it proceeds to print the recipe formatted properly.

![2021-03-22-022132_1312x953_scrot](https://user-images.githubusercontent.com/38867904/111926396-f7b87100-8aac-11eb-946e-78b898ae44f7.png)

Executable as well as source is found here: [~knarkzel](https://git.sr.ht/~knarkzel/based). I haven't tested it enough yet so might be scuffed.

**Comment by hallzy** [comment]
integrating this into the PR workflow might be useful.

That workflow already checks for some things like file names.

I just submitted a PR to add more checks #400

**Comment by Knarkzel** [comment]
Sweet. Just let me know if anything is missing or if it's difficult to integrate. At the moment it's a very rough draft, but should work (I hope lol).

**Comment by teunissenstefan** [comment]
You could also always convert the filename to lowercase instead of throwing an error if it isn't fully lowercase.

**Comment by Knarkzel** [comment]
Latest binary can be downloaded like so:
```sh
curl -LO https://git.sr.ht/~knarkzel/based/blob/master/bootstrap.sh
sh bootstrap.sh
```

**Comment by m-chrzan** [comment]
Some sanity checks in GitHub actions would be nice.

So far everything has been done with bash scripting, adding the entire Rust toolchain as a dependency doesn't feel like the right tool for the job. Whatever tool ends up doing these checks should be part of this repo, not an externally downloaded binary.

**Comment by Knarkzel** [comment]
An externally downloaded library is just one option (for less dependencies and faster runtime). Adding the Rust toolchain is as simple as `pacman -S rust` or whatever the distro used in the build is.
