### ISSUE TITLE
CI is broken?

### ISSUE THREAD

**Issue by hallzy** [LukeSmithxyz/based.cooking#413]
https://github.com/LukeSmithxyz/based.cooking/runs/2167818942?check_suite_focus=true

Looks like the continuous integration is broken so the website isn't updating.

```
======CMD======
cd repo
git pull --force origin master
make clean deploy

======END======
err: From https://github.com/lukesmithxyz/based.recipes
err:  * branch            master     -> FETCH_HEAD
err:    fa1d270..dda5820  master     -> origin/master
out: Updating df8034e..dda5820
err: error: Your local changes to the following files would be overwritten by merge:
err: 	Makefile
err: Please commit your changes or stash them before you merge.
err: Aborting
```

But then it goes on to do the build process and claims to have succeeded.

However, the website doesn't look like it has updated in a while so something seems off here.

**Comment by z7o** [comment]
Could it be the cache? Have you tried F5 R, if not you can try that!

**Comment by hallzy** [comment]
Yes I have.

Example of a page that is committed to git but not on the page is [Pasta Alla Norma](https://based.cooking/pasta-alla-norma). Commit is [here](https://github.com/LukeSmithxyz/based.cooking/commit/fa1d2706b33d873d6165e338380ad59416df6e01)

**Comment by hallzy** [comment]
derp, I'm so dumb. For some reason that output I had in my first comment confused me.

Now that I have my head on straight, it is pretty clear that the reason the website is not updating is because there is a local change on the web server to the Makefile. When we try to pull the latest changes from github it fails because the makefile has a local change and the updates from github can't be merged in.

The build process afterwards probably succeeds but it is building the old files, not the new files.

Luke will have to go onto the server and see what the local change is.

[this](https://github.com/LukeSmithxyz/based.cooking/commit/b40f0f43afb37b669837b86c1557042cb3ee9dcc) looks like it was the first commit to not work, and it is a change to the makefile by Luke. So maybe Luke was testing this Makefile change on the server locally and forgot to remove it so that the git pull would work?

including @LukeSmithxyz

**Comment by hallzy** [comment]
I'll probably make a PR to try and fix the CI though, because it comes back saying that it is passing but it clearly isn't because the git pull is failing
