### ISSUE TITLE
Using IPFS for Decentralized hosting

### ISSUE THREAD

**Issue by zyansheep** [LukeSmithxyz/based.cooking#420]
Consider using IPFS where hosting is less demanding, it is decentralized, versioned, and archivable.
#368 allows people to build and host their own copy of the website on ipfs.

**Comment by DGKSK8LIFE** [comment]
Wow yeah it seems like loadtimes are a lot faster with IFPS. But haven't actually benchmarked yet.

**Comment by LukeSmithxyz** [comment]
I'm a boomer and I don't know about IPFS. I might look into it, but I won't switch until I'm highly familiar with the technology.

**Comment by zyansheep** [comment]
@LukeSmithxyz could you merge #368 anyway so I can setup an always-up-to-date version of the website? (the current website is slow to update sometimes...) It will work by periodically pulling for commits at the remote, running the `ipfs-deploy` build target and then updating the DNS record to point to the new IPFS address.
