### ISSUE TITLE
Offer HTTP/2

### ISSUE THREAD

**Issue by MGislv** [LukeSmithxyz/based.cooking#430]

**Comment by taco-c** [comment]
Could you elaborate?

**Comment by DGKSK8LIFE** [comment]
> Could you elaborate?

It seems like he wants HTTP/2 protocol support.

**Comment by MGislv** [comment]
> > Could you elaborate?
> 
> It seems like he wants HTTP/2 protocol support.

Yes, I should have been more explicative.
Thanks anyway
