### ISSUE TITLE
No "main" in html template ?

### ISSUE THREAD

**Issue by HappyClem** [LukeSmithxyz/based.cooking#431]
Is there any reason for why there isn't <main> tag ?

**Comment by Knarkzel** [comment]
Why would <main> be necessary? We don't do soydev stuff here.

**Comment by HappyClem** [comment]
It helps SEO and even readability I think ? Not necessary to be sure, but for what it cost, why not ?

**Comment by almaember1098** [comment]
It *might* (I'm not sure) also help people with screen readers, so it could have a point

**Comment by DGKSK8LIFE** [comment]
> It helps SEO and even readability I think ? Not necessary to be sure, but for what it cost, why not ?

`<meta></meta>` can improve SEO a lot more than a simple main tag (https://www.w3schools.com/tags/tag_meta.asp)

**Comment by HappyClem** [comment]
[ARIA Maint tag](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Main_role)

**Comment by almaember1098** [comment]
> does it as well. And it actually can help for accessibility, which is a great think to think of.

That's the most important part, it probably does not make SEO that much better

**Comment by DGKSK8LIFE** [comment]
Agreed. Though you could have accessibility features like TTS implemented with an `alt` property. Either way, the overall goal is to have as little html/css to render per recipe and also have the best UX/accessibility at the same time.

**Comment by LukeSmithxyz** [comment]
If there is a tangible reason to add this, open a PR and list why.
