### ISSUE TITLE
Open to a new way of building the site.

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/based.cooking#444]
I like the blogit makefile thing, but it takes a long time to compile because it has to do a million loops per file to get all the info and has yielded quite a few bugs so far. blogit would probably run a bit faster if it used mostly `read`, but I think that's not something I want to work on.

If anyone wants to give another way of compiling the site, feel free to. This might include a static site generator that can give me a new front page as the articles are getting more numerous.

The only big requirement it needs is tagging at least analogous to what we have and that could serve as a drop-in replacement.

**Comment by Socerest2** [comment]
I don't have a specific way, but, if the website could compile css menus per tag. Example lets say Recipe A is tagged american and dessert. The website would make menus per each tag, and put the recipe in each tag menu. This can minimize a bunch of recipes on the one page.

**Comment by arnpatel** [comment]
Have you considered leveraging GitHub Page's resource by using Jekyll as the static site generator? That eliminates the need to use your Vultr server, and enables us to directly have GitHub via automation handle .md to .html conversion per specified parameters and stylesheets. 

Sorry in advance if you ever mentioned before in live stream to not use Jekyll, but I never heard you say that.

If you want to consider this thought, I have a template ready which I can send you as a proposal for change.

**Comment by LukeSmithxyz** [comment]
I'm not going to host with Github.

I'm not necessarily against Jekyll or Hugo or something. I've used them in the distant past, but I'm sure I'll try to implement them and inevitably find they add stupid stuff or a 300k of unreadable source code to every page, knowing how even "minimalist" static site generators are.

**Comment by DGKSK8LIFE** [comment]
@LukeSmithxyz You could implement Jekyll with the current setup you have. Just need to do a bit of tweaking. I think eventually for a better user experience/a more seamless way of uploading recipes (doing it through `based.cooking` via an upload system), you will need a proper database and server-side business logic. And eventually, if you want to implement said functionality, you will probably need to write some Javascript. A static-site generator (such as blogit) will become tedious to maintain and deal with as the application scales up.

**Comment by LukeSmithxyz** [comment]
Okay. Jekyll is out of the question then.

**Comment by DGKSK8LIFE** [comment]
Would you be open to potentially using a Database server like MySQL as the amount of recipes scale up? @LukeSmithxyz

**Comment by JohnHolmesII** [comment]
That is the absurd mentality that leads to bloat. There is really no need for a database server.

**Comment by DGKSK8LIFE** [comment]
Yeah agreed. Just thinking about the future of the site beyond a static site generator. @JohnHolmesII

**Comment by LukeSmithxyz** [comment]
This is a static site. It will always be a static site. This site was literally founded to be a static site.

**Comment by HappyClem** [comment]
I have been looking at Zola for some days now. It seems better than Jekyll for sure (and easy enough for noob like me, not that it matters for you.
Here's a look to [Zola homepage](https://www.getzola.org/)

**Comment by hngt** [comment]
Why not rewrite blogit functionalities to a compiled programming language? Go or C could easily do string concatenation and keeping each tag in their place in parallel. Rewriting stuff to template based system is problematic enough.

The question is whether there is a will to make one, as this project is something that will take a bit of time (might work on it on the weekend if anyone is interested).

**Comment by DGKSK8LIFE** [comment]
> Why not rewrite blogit functionalities to a compiled programming language? Go or C could easily do string concatenation and keeping each tag in their place in parallel. Rewriting stuff to template based system is problematic enough.

> The question is whether there is a will to make one, as this project is something that will take a bit of time (might work on it on the weekend if anyone is interested).

Well it seems like this would just be supplemental effort for functionality that's already satisfied by Static Site Generators like Hugo, Strapi, Gatsby, Blogit (though there have been problems), etc. I'd be willing to work on something like what you proposed this weekend I'd just like the get the greenlight from @LukeSmithxyz before we move forward.

**Comment by hngt** [comment]
> > Why not rewrite blogit functionalities to a compiled programming language? Go or C could easily do string concatenation and keeping each tag in their place in parallel. Rewriting stuff to template based system is problematic enough.
> 
> > The question is whether there is a will to make one, as this project is something that will take a bit of time (might work on it on the weekend if anyone is interested).
> 
> Well it seems like this would just be supplemental effort for functionality that's already satisfied by Static Site Generators like Hugo, Strapi, Gatsby, Blogit (though there have been problems), etc. I'd be willing to work on something like what you proposed this weekend I'd just like the get the greenlight from @LukeSmithxyz before we move forward.

Each of them uses senseless internals or is too slow. Having an in-house solution would stop us from having to revise all recipes, and we wouuld be able to add functionalities we want directly.

**Comment by pyzozord** [comment]
The real chad way is to write your own markdown-to-html compiler in awk or use something like https://github.com/nuex/zodiac

**Comment by the3dfxdude** [comment]
So Make is a good system for automating a process to command execution. But if you start embedding scripts and the steps share alot of data, you are better off bringing that into a complete script of its own. Converting the Makefile into the script intended is the task required here.

I've converted the core of the generation process (articles and tag filter pages) into a script, so about 50% done in about an hour. Basically it's a direct conversion of what Make did into a new script, using the same shell commands. Then I started passes at optimizing the external shell commands into internal commands. Now I can see the issue with the Makefile. It was basically reading the md files again and again at every step. Basically using Make without any benefit, because it pretty much needed to read every file again to know what to do every step, even if nothing need to be written on some steps.

Anyway, I was initially resistant to the management ideas that the blogit had, but I am coming around to it, after optimizing it. I thought it was just going to be a burden and wanted to suggest other ways. Anyway I am using tried and true methods having done similar generators, but keep the same system so it will be a drop in replacement.

Note: I was likely going to write this system anyway, for my own stuff. This is why I wanted to do it a bit different, because when I saw Luke suggesting blogit in the video a week ago, I was concerned about it. And I haven't found a static gen system that I've liked for searching for months now.

**Comment by DGKSK8LIFE** [comment]
> > > Why not rewrite blogit functionalities to a compiled programming language? Go or C could easily do string concatenation and keeping each tag in their place in parallel. Rewriting stuff to template based system is problematic enough.
> > 
> > 
> > > The question is whether there is a will to make one, as this project is something that will take a bit of time (might work on it on the weekend if anyone is interested).
> > 
> > 
> > Well it seems like this would just be supplemental effort for functionality that's already satisfied by Static Site Generators like Hugo, Strapi, Gatsby, Blogit (though there have been problems), etc. I'd be willing to work on something like what you proposed this weekend I'd just like the get the greenlight from @LukeSmithxyz before we move forward.
> 
> Each of them uses senseless internals or is too slow. Having an in-house solution would stop us from having to revise all recipes, and we would be able to add functionalities we want directly.

Agreed, but I'm not sure if the project is at the point where it's necessary yet. Could you describe your proposed in-house solution more and what the architecture/functionality would look like? Thanks

**Comment by the3dfxdude** [comment]
I finished up last week my static site generation script using Perl. I'll be using it on my own site soon. It tested successfully on based.cooking as well, with all the same features, except now doesn't require all the shell commands or loops -- it's as integrated as could be without deviating.

**Comment by TrevCan** [comment]
Hey, I've recently encountered a simple static site generator written mainly in `sh`. It's called mkws.sh (https://mkws.sh/) and is quite simple (just shell scripts) , just add `*.upphtml` files and it will automatically transform them into `*.html` files. What's cool about this is that it allows you to embed shell script within these files, e.g. allowing to run a markdown processor which will output data into HTML. So, maybe, set up a make file which does the following: for each recipe file (written in markdown) create an `.upphtml` file with the code which will process the Markdown into html. And for each html file geneated, create an index.html file which adds each of these.

**Comment by adriangrigore** [comment]
> So, maybe, set up a make file which does the following: for each recipe file (written in markdown) create an .upphtml file with the code which will process the Markdown into html. 

Just run the `Markdown` processor in the `share/l.upphtml` file and loop through the recipes in the `Makefile` (if you prefer) or `bin/mkws` file. No need to create an `.upphtml`  for each recipe.

**Comment by TrevCan** [comment]
@adriangrigore sounds great! I guess this is quite  a good solution then.

**Comment by adriangrigore** [comment]
I doesn't have the tagging functionality but I believe it's not that hard to add with a small parser.

**Comment by adriangrigore** [comment]
Why aren't you storing the `HTML` files in `git`, that way, you don't have to rebuild the whole web site for every new recipe?

**Comment by TrevCan** [comment]
Yeah, that seems like the soundest way to go, otherwise build times will increase a lot. Combined with some git magic, some automated workflow (maybe on Github) could check if the files have been modified and therefore trigger a build for the new changed files only.

**Comment by adriangrigore** [comment]
> Combined with some git magic, some automated workflow (maybe on Github) could check if the files have been modified and therefore trigger a build for the new changed files only

That's what the  `Makefile` does.

**Comment by adriangrigore** [comment]
Ok, I played a little with https://mkws.sh, this is what I ended with until now:

```bash
#!/bin/sh
PATH=./bin:$PATH

usage() {
	>&2 printf "usage: %s url [path]\\n" "$(basename "$0")"
	exit 1
}

test $# -lt 1 && usage

export src=${2:-.}
export public="$src"/public
export share=${MKWSTHEMEDIR:-"$src"/share}
export LANG=${LANG:-en_US.UTF-8}

if ! test -f "$src"/index.upphtml
then
	>&2 printf "no index.upphtml file found\\n"
	exit 1
fi

if test "$share"/s.uppcss -nt "$public"/s.cs
then
echo "Making s.css"
pp "$share"/s.uppcss "$1" > "$public"/s.css
fi

for f in "$src"/src/*
do
	o="$public"/$(basename "${f%.md}".html)

	test "$0" -ot "$o" &&
	test -f "$o" &&
	test "$share"/s.uppcss -ot "$o" &&
	test "$share"/l.upphtml -ot "$o" &&
	test "$f" -ot "$o" && continue

	echo "Making $(basename "${f%.md}".html)"
	TITLE="$(head -1 "$f" | cut -c 3-)" \
	PAGETITLE="$TITLE Recipe -- Based Cooking" \
	AUTHOR="$(git log --format="%an" -- "$f" | tail -n 1)" \
	POSTED="$(git log -n 1 --diff-filter=A --date="format: %F" --pretty=format:'%ad' -- "$f")" \
	EDITED="$(git log -n 1 --date="format: %F" --pretty=format:'%ad' -- "$f")" \
	TAGS="$(grep -i '^; *tags:' "$f" | cut -d: -f2-)"
	pp "$share"/l.upphtml "$f" "$1" > "$o"
done

all=$(ls -1 src | sed "s/.md//g" | sort)
oall=$(find "$public"/ -name '*.html' ! -name '@*' ! -name 'index.html' | sed -E "s#^$public/(.*).html#\1#g" | sort)
tags=$(grep -hi '^; *tags:' src/* | cut -d: -f2- | tr ' ' '\n' | sort | uniq | sed 1d)
otags=$(find "$public" -name "@*" | sed -E "s#^$(echo "$public" | sed 's/\./\\./g')/@([a-z]+).html#\1#g" | sort)

if
test "$0" -nt "$public"/index.html ||
test "$share"/s.uppcss -nt "$public"/index.html ||
test "$share"/l.upphtml -nt "$public"/index.html ||
test "$tags" != "$otags"
then
for t in $tags
do
	echo "Making @$t.html"
	grep -l "$t" src/* |
	PAGETITLE="Articles tagged $* -- Based Cooking" \
	TITLE="Based Cooking" \
	TAGS="$tags" \
	pp "$share"/l.upphtml tag.upphtml > "$public/@$t.html"
done
fi

if 
! test -f "$public"/index.html ||
test "$0" -nt "$public"/index.html ||
test "$share"/s.uppcss -nt "$public"/index.html ||
test "$share"/l.upphtml -nt "$public"/index.html ||
test "$tags" != "$otags" ||
test "$all" != "$oall" ||
test index.upphtml -nt "$public"/index.html
then
echo "Making index.html"
PAGETITLE="Based Cooking" \
TITLE="Based Cooking" \
pp "$share"/l.upphtml index.upphtml > "$public"/index.html
fi

if
test "$0" -nt "$public"/sitemap.xml ||
test "$share"/sitemap.uppxml -nt "$public"/sitemap.xml ||
test "$tags" != "$otags"
test "$all" != "$oall"
then
echo "Making sitemap.xml"
pp "$share"/sitemap.uppxml "$1" > sitemap.xml
fi

if
test "$0" -nt "$public"/rss.xml ||
test "$share"/rss.uppxml -nt "$public"/rss.xml ||
test "$all" != "$oall"
then
echo "Making rss.xml"
pp "$share"/rss.uppxml "$1" > "$public"/rss.xml
fi

if
test "$0" -nt "$public"/atom.xml ||
test "$share"/atom.uppxml -nt "$public"/atom.xml ||
test "$all" != "$oall"
then
echo "Making atom.xml"
pp "$share"/atom.uppxml "$1" > atom.xml
fi
```

I added caching also.

Probably a combination of `blogit` and https://mkws.sh/pp.html would be better.

**Comment by Demonstrandum** [comment]
There's no need to store HTML build files in the git  repository, they should and can easily be persistent server side.

**Comment by binex-dsk** [comment]
Write it in C
