### ISSUE TITLE
Script to semi-automate recipe creation

### ISSUE THREAD

**Issue by sylGauthier** [LukeSmithxyz/based.cooking#466]
I extended my `cook` script to also offer an interactive recipe generation system. It performs some basic sanity checks and generate a proper, clean markdown file. There's still some issues so if you're using it, don't forget to proof read the markdown file before submission.

Get it [here](https://github.com/sylGauthier/cook)

Just type `cook -n` to create a new recipe using the interactive system. Hopefully this helps improving the workflow and quality of the recipes.

Ideally I'd extend it to grep for keywords in other recipes and offer to link recipes between each other, since people aren't doing it as much as they should.

**Comment by zyansheep** [comment]
Seems like something to add to the README.md?
