### ISSUE TITLE
Measurements? 

### ISSUE THREAD

**Issue by Karl-Webster** [LukeSmithxyz/based.cooking#49]
First I am a big fan of your content. But just saying the following:
```
chicken breasts 
tomatoes (San Marzano is best) 
mozzarella cheese
parmesan cheese
bread crumbs
eggs
flour
pasta sauce
```
That gives lots of room for error, perhaps if you could standardise on ingredients for 2 persons as that way if you are cooking solo you can keep leftovers and its easy to multiply by how many people you need to cook for. 

Maybe I am just being a smoothbrain but I know 100% if I try to follow this I will get it wrong, while I know it does not require the amount of an ingredient to count as a  "recipe" it would be extremely helpful.

**Comment by DarkWiiPlayer** [comment]
Using which units though?

**Comment by Karl-Webster** [comment]
Taken from the Readme:
```
If measurements are used, include metric and American measurements. Do not use decimals in American; round or use fractions.
```

**Comment by neuhaus** [comment]
This should also apply to the temperatures given. I saw a recipe that only stated Fahrenheit.

It would perhaps be best if there's optional automatic unit conversion (with some Javascript?)

**Comment by Karl-Webster** [comment]
My understanding of the project is that JS is a no-go. I am not opposed to manually converting units and making a PR.

**Comment by DarkWiiPlayer** [comment]
> It would perhaps be best if there's optional automatic unit conversion (with some Javascript?)

Ugh please no. If anything, add the units to the HTML somehow and if anybody wants a conversion script, they can write their own (it's what I had in mind anyway)

**Comment by giovanni-orciuolo** [comment]
A simple JS unit converter would be enough, but apparently even 1 line of JS is considered bloat

**Comment by DarkWiiPlayer** [comment]
One line of JS isn't bloat, but a unit converter is just one feature of many that, on their own would be a cool addition, but in their sum would bloat the page.

**Comment by Aeredren** [comment]
https://www.gnu.org/software/units/units.html

Units is a nobrainer since Unix as been around guys

**Comment by DarkWiiPlayer** [comment]
I still think it'd be nice to have some sort of machine-readable formatting for units though:

`Add <data value="300 g">a fuckton</data> of salt`
