### ISSUE TITLE
ASKING FOR HELP, 

### ISSUE THREAD

**Issue by marttoygoy4** [LukeSmithxyz/based.cooking#506]
So there is this website I used to use it in 2008 I think sTILLL UP!!! WTF? 
I am thinking of building a crawler and merging it to based.cooking since its redpilled 
![image](https://user-images.githubusercontent.com/80398595/112719190-b7bc1880-8f08-11eb-9920-ebbf3ffca5be.png)

You guys think it would be nice to archive this website inside based.cooking ? Recently I got a nostagia vibes (midlife hipster moment) I wanna archive it thinking of making a crawler and getting all of the shit from there :D and into a markdown files

I wanna cry :( back in the days we could have a message board on everything discuss, whats the point of the only place of gardering is few fatfucks on IRC and twitter ? What happen to Yahoo chat and geocities

**Comment by marttoygoy4** [comment]
![image](https://user-images.githubusercontent.com/80398595/112719437-1209a900-8f0a-11eb-8d7a-228769b0851e.png)
Hahaha help me in my midlife crisis fuck that shit, the internet is dead image is very related

**Comment by hngt** [comment]
> Recipe Cottage © 1994 - 2005.  All Rights Reserved.

You can copy all recipes from based.cooking to recipecottage though.

**Comment by Holsterbau** [comment]
He's having an attack. He has an insulin problem, someone give him some candy.

**Comment by DGKSK8LIFE** [comment]
> He's having an attack. He has an insulin problem, someone give him some candy.

Another reason to have special diet categories lol #508

**Comment by Dko1905** [comment]
> Another reason to have special diet categories lol #508

That was **smoooooooth**
