### ISSUE TITLE
Live Search with RSS (Feature Request)

### ISSUE THREAD

**Issue by jacobsammon** [LukeSmithxyz/based.cooking#530]
I know that on a computer it's easy to search recipes with `CTRL` + `F`, but on mobile it's much harder -- not even a feature on some browsers.

My idea was that this project of W3Schools could be adapted: https://www.w3schools.com/php/php_ajax_livesearch.asp. It does use Javascript, but for live searching there's no real alternatives. In the tutorial, they use an XML sheet with their page title and link in, this could be changed to use the RSS feed the site generator makes, so adding new recipes would be automatic.

**Comment by post-rex** [comment]
This is supposed to be a static site, if I get this right the search is server side.
Maybe we can collect all the receipt from the website using JavaScript after it loaded and then provide a simple search bar?
Personally I think that might be an acceptable use case for JavaScript on this website, but its up to Luke I guess.

**Comment by jacobsammon** [comment]
Sort of. All the PHP does is search the XML (RSS feed).

The reason I recommended this particular solution is because of how it'd work with the entire static site's already existing RSS feed, and would all be done automatically.

As you say - it's up to Luke.

**Comment by DGKSK8LIFE** [comment]
What would be nice with a custom RSS Feed is a notification system or weekly report of new recipes. Not really the functionality of a static site but it could be very helpful.
