### ISSUE TITLE
Add the possibility to create accounts

### ISSUE THREAD

**Issue by LongJohn-Silver** [LukeSmithxyz/based.cooking#562]
I know the idea is for the website to be as simple as possible, but I think it would be awesome so be able to create accounts, that way you could save recipes you like and even submitting recipes through your account.

**Comment by WitherCubes** [comment]
What @Yaroslav-95 says is right, bookmark the recipes you want and please close this issue.

**Comment by DGKSK8LIFE** [comment]
Yeah I don't think @LukeSmithxyz will approve of tihs. An account system requires lots of business logic (such as database storage, hashing credentials, authorization, etc) or if you were to use an auth-as-a-service system you'd be writing lots of Javascript.
