### ISSUE TITLE
RSS failed

### ISSUE THREAD

**Issue by mlunax** [LukeSmithxyz/based.cooking#630]
One recipe makes RSS and ATOM dead.
![image](https://user-images.githubusercontent.com/11018865/118935012-54b89200-b94b-11eb-85d5-428dfd7eb2a4.png)

**Comment by DGKSK8LIFE** [comment]
Yup. Looks like that character will have to be escaped with: `&amp;`.

**Comment by mlunax** [comment]
Why not make script for thats?
