### ISSUE TITLE
Tanzania Tea Recipe is NOT Based

### ISSUE THREAD

**Issue by InternetAnon** [LukeSmithxyz/based.cooking#632]
https://based.cooking/tanzania-tea-with-milk.html

This recipe suggests black tea with milk and sugar originated in Africa, which is absurd.
The British were the first to popularize this drink. It should be called British Tea.
The Chinese discovered tea, experimented with different ingredients, then sold it to the British in the 17th century, who added milk and sugar.
All of this has happened.

Tanzania does grow its own tea, but the recipe just calls for Ceylon black tea, which is another name for Sri Lanka black tea. How many countries do we need in this recipe? Let's cut out the bloated middlemen and just call it British Tea.

**Comment by DGKSK8LIFE** [comment]
Username checks out, description checks out, unbased issue, please close,

**Comment by DGKSK8LIFE** [comment]
@LukeSmithxyz close this.

**Comment by Makrennel** [comment]
He's not wrong, it's literally just milk tea like any other.
