### ISSUE TITLE
'&' in 'Chorizo & Chickpea Soup' breaks RSS

### ISSUE THREAD

**Issue by esantoro** [LukeSmithxyz/based.cooking#635]
Hello,
the '&' in 'Chorizo & Chickpea Soup' at `src/chorizo-and-chickpea-soup.md` breaks RSS file as the '&' is not properly escaped in the resulting XML file.

This is a bug in the underlying software, blogit, if my understanding is correct.

However, to quickly fix the issue for this specific project, you might want to replace '&' with 'and' in the title for this recipe.

**Comment by esantoro** [comment]
Link to the broken RSS file: `https://based.cooking/rss.xml`

Screen:
![image](https://user-images.githubusercontent.com/34766/119223435-b7e82700-baf9-11eb-9f83-0effa440496e.png)

Of course the problem is also visible in RSS readers (I'm using liferea, but should be the same in other softwares)

**Comment by DGKSK8LIFE** [comment]
You don't need to. You simply need to escape the ampersand. I fixed this in #631

**Comment by esantoro** [comment]
cool!
