### ISSUE TITLE
website security issues

### ISSUE THREAD

**Issue by dennis-ritchie2** [LukeSmithxyz/based.cooking#64]
based?
based on what?

**Comment by Goblin80** [comment]
> The quality of having an opinion without regard for what other people think, often a controversial opinion but not always. Upon expressing such an opinion it is customary for others to acknowledge the person as being based.

https://www.urbandictionary.com/define.php?term=Based

**Comment by sysgrammer** [comment]
Why is this stupid issue not closed?

**Comment by DickFaggotson** [comment]
> Why is this stupid issue not closed?

Shut up, dweeb.

**Comment by lisbonjoker** [comment]
> Why is this stupid issue not closed?

Stupid? It's quite an important question he is making.

**Comment by DGKSK8LIFE** [comment]
Yeah please elaborate @dennis-ritchie2

**Comment by Dko1905** [comment]
@LukeSmithxyz This issue should be closed.

**Comment by lisbonjoker** [comment]
It has not been resolved yet, @Dko1905. The website still has this high priority security issue to be resolved.

**Comment by Dko1905** [comment]
> It has not been resolved yet, @Dko1905. The website still has this high priority security issue to be resolved.

I cannot see any valid issue here.

**Comment by Holsterbau** [comment]
![keycap_rick](https://user-images.githubusercontent.com/20506147/112872271-766e6900-90c0-11eb-984b-32f734465d10.png)

**Comment by DGKSK8LIFE** [comment]
@LukeSmithxyz close plz

**Comment by lisbonjoker** [comment]
> I cannot see any valid issue here.

It's right there, @Dko1905:
> based?
> based on what?

**Comment by ultrablasta** [comment]
> based?
> based on what?

based on cooking 🧑‍🍳 

duh 🙄

**Comment by Argo00** [comment]
lol, is this still really open?

**Comment by lisbonjoker** [comment]
> > based?
> > based on what?
> 
> based on cooking cook
> 
> duh roll_eyes

Still not exactly clear, please provide a more detailed explanation.
