### ISSUE TITLE
Enable unencrypted HTTP access

### ISSUE THREAD

**Issue by schreiberstein** [LukeSmithxyz/based.cooking#647]
There is no confidential information exchanged.
Why not offer regular unencrypted HTTP access via port 80 without redirecting to HTTPS?
There are many "legacy" browsers that cannot access this site due to cryptonerds' fetishization of HTTPS, despite being more than capable of displaying it.

**Why can this website not be accessed on a real, enterprise-grade web browser such as Microsoft Internet Explorer 5?**

**Comment by hallzy** [comment]
lol

**Comment by Refalm** [comment]
https://www.troyhunt.com/heres-why-your-static-website-needs-https/

**Comment by LukeSmithxyz** [comment]
Lol
