### ISSUE TITLE
Oats recipie uses water ( bad :< )

### ISSUE THREAD

**Issue by peepopoggers** [LukeSmithxyz/based.cooking#658]
How will your bones become strong with water? Milk is based.

Is it acceptable to submit a pr which edits the oats recipie to have instructions for both water and milk?

thanks.

**Comment by adrylain** [comment]
Add it as an option. Some of us are lactose intolerant. :(

**Comment by peepopoggers** [comment]
> Add it as an option. Some of us are lactose intolerant. :(

well almond milk or substitutes could also be a valid option too
