### ISSUE TITLE
bug-recipe pages double entries

### ISSUE THREAD

**Issue by wdunkelheit** [LukeSmithxyz/based.cooking#693]
Some recipe pages have rendered from markdown twice such as 

+ https://based.cooking/ragu-napoletano.html
+ https://based.cooking/chorizo-and-chickpea-soup.html
+ https://based.cooking/mapo-tofu.html

There is likely more.

**Comment by wdunkelheit** [comment]
clarification: the html page contents have rendered twice from markdown

**Comment by hallzy** [comment]
DUP: #552 #633 #659 #685

**Comment by hMihaiDavid** [comment]
![mmmh](https://user-images.githubusercontent.com/24855110/134353071-6b5c3e37-f226-4d5f-a4bd-adfb448eacc3.png)
Here's an example of how it looks like fwiw

**Comment by jamescrake-merani** [comment]
The chocolate chip recipe seems to do that as well.

https://based.cooking/chocolate-chip-cookies.html
