### ISSUE TITLE
Implent recipe schema

### ISSUE THREAD

**Issue by yagarea** [LukeSmithxyz/based.cooking#694]
Hello, I suggest to implement standard  recipe schema for easy parsing by other software.

Here is recipe schema specification: [https://schema.org/Recipe](https://schema.org/Recipe)

It is minimal change to site but huge rise of potential usages.

**Comment by wups** [comment]
I think this is out of scope for this project. This website needs simple, human writable markdown files and simple, human readable html files. It does only one thing. Using the schema from schema.org (which is not very readable, e.g. `prepTime: PT15M`) would require an (for its main task) unnecessary additional/intermediate step to convert the data.

The data is freely available on Github, so everyone can create a tool / script / program / additional repository that converts the recipes into whichever schema they want. It doesn't need to be integrated into the site.
