### ISSUE TITLE
The style of icon images is broken when using browser translation

### ISSUE THREAD

**Issue by YiJisol** [LukeSmithxyz/based.cooking#699]
<img width="960" alt="Screenshot" src="https://user-images.githubusercontent.com/48981593/133517279-5f91b4f7-6a02-416f-a8b7-80d8cdc51771.png">

Because browsers translate alt texts.

Turning on the translation feature breaks the layout. When I first came to this site, it was quite confusing because translation was turned on from the beginning.

I would suggest using class instead of attribute selector.

**Comment by Obazzi** [comment]
noodle dome
