### ISSUE TITLE
create new tags for vegan\vegetarian\non vegetarian dishes

### ISSUE THREAD

**Issue by Tintedfireglass** [LukeSmithxyz/based.cooking#720]
would be nice to separate dishes by vegan, vegetarian and non vegetarian

**Comment by Tintedfireglass** [comment]
would be nice to separate dishes by vegan, vegetarian and non vegetarian

**Comment by tfasano1** [comment]
Maybe for bugman.cooking...

**Comment by goolord** [comment]
![image](https://user-images.githubusercontent.com/24906808/193975912-1f52b1b7-7cb9-4c05-955e-68691c119646.png)

**Comment by colleen05** [comment]
this would be good...
