### ISSUE TITLE
can someone explain how to build the website on my own server

### ISSUE THREAD

**Issue by liam8888999** [LukeSmithxyz/based.cooking#732]

**Comment by ThamognyaKodi** [comment]
There is a make file that you should look into. Also for more information you can look into #444, #452 and few of the other issues.

**Comment by liam8888999** [comment]
thanks. that doesn't really help. I am trying to fork it and build to run on a server that has no internet connection but I guess I will just have to make html files for each recipe

**Comment by tfasano1** [comment]
If you want to run an http server locally you can type `python -m http.server` and it will run on port 8000, then point your browser to `localhost:8000`.
As far as the makefile I'm not sure because I've never looked at it.

**Comment by liam8888999** [comment]
> Type `make build` . The html will be in the blog folder.
> 
> If you want to run an http server locally you can type `python -m http.server` in the blog folder and it will run on port 8000, then point your browser to `localhost:8000`.
> 
> If you're doing this on a raspberry pi or some other machine with no Internet, you can substitute `localhost` with it's local ip address to view the site on your desktop over the LAN.

roughly how long does the make build command take and does it need to be re run for every added recipe

**Comment by tfasano1** [comment]
> > Type `make build` . The html will be in the blog folder.
> > If you want to run an http server locally you can type `python -m http.server` in the blog folder and it will run on port 8000, then point your browser to `localhost:8000`.
> > If you're doing this on a raspberry pi or some other machine with no Internet, you can substitute `localhost` with it's local ip address to view the site on your desktop over the LAN.
> 
> roughly how long does the make build command take and does it need to be re run for every added recipe

It depends on how fast your machine is, just run the command and find out. Yes it would need to re run for every new recipe which is why this project has had a hiatus.
