### ISSUE TITLE
Let's revive the project!

### ISSUE THREAD

**Issue by v0iden** [LukeSmithxyz/based.cooking#748]
I think it's a shame that this project died. It had such potential. It's ironic how the simplicity actually made things more complicated in the end.

**Comment by pokemonsta433** [comment]
I think the ultimate way to do something like this is an object-oriented app. Have ingredients list be a list of ingredient objects that have a quantity, type, and prep (so "2 small tomatoes, diced" becomes {food=tomato; quantity=2; prep=diced; notes=small}) and then you could use this information to create grocery lists (and add ingredients from multiple recipes together), searches, etc. Also if it's an app we can just have the html database be much larger and you just set your custom css and display preferences etc. I plan to make this at *some* point.

But what's the issue with the project as-is? I haven't been following it too closely but the site seems pretty useable

**Comment by pokemonsta433** [comment]
sry not sure if this was clear enough, but like my idea is that you would basically download recipes (or recipe packs, which might be not even a bad idea) like you would a package with yay. And then you can just query the database of recipes the same way you do any database. That way you can only download/keep recipes you like, so you have a much easier-to-use recipe list  ("like a my-saved recipes") locally, and we can do vim-like navigation in-app (n for next step in the instructions list, +/- to change text-size, j/k do exactly what you'd expect, etc.). And again the rendering locally means you can do your own ricing for whatever display you want to use (and maybe some way to send to pdf for printing, but that's for not-me to write)

**Comment by v0iden** [comment]
the project hasn't been updated with new recipes in many months, despite countless pull requests. from what I understand is this because building the website takes a long time for Luke with the current setup. I would def prefer this to stay as a website, I see no point in making it even more niece than it already is. I support the object-oriented part though, I think better machine readability is important regardless.
