### ISSUE TITLE
Site will be Redone in Hugo

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/based.cooking#750]
I haven't touched this site in like a year because the static site generator used was hobbled-together and couldn't scale without constantly breaking and taking minutes to recompile.

I've decided to switch to Hugo to compile the site, and I hope to finish this in the next week. I didn't switch before because Hugo themes are kind of a pain to specialize for the unfamiliar, but I've since gained familiarity with it enough that I can confidently make a setup perfectly to my vision for the site.

I'll use this as an opportunity to make other improvements to the site.

Note that I still do not want to drastically increase the number of recipes right now. In fact, in the future, I might slim them down to undebatably "based" recipes only. (I am no longer ignoring notifications from this git repository.)

**Comment by v0iden** [comment]
awesome news!

**Comment by peepopoggers** [comment]
Based, Redpilled, and Mental Outlaw's alter deepfake :cat: :+1:

**Comment by peepopoggers** [comment]
Btw, just some ideas: maybe add reviews section to recipes somehow? I know it is meant to be static, but it would be nice to know if what I am making is good/accurate or not.

**Comment by LukeSmithxyz** [comment]
The Hugo version of the site is now up. Doesn't look much different, but infinitely easier to manage and compiles in milleseconds. I'm going to start by organizing and systematizing tags and such, then add other improvements.

**Comment by LukeSmithxyz** [comment]
I've added all the author names into metadata, so I don't have to fret about people refusing to follow the formatting guidelines lol

Might add cook/prep time to metadata in the future.

Site is very clean on the backend now. I'm still mastering hugo to do all I want, but I'm feeling like I might start looking at new submissions and maybe I'll start curating things a little more since it's easier.

**Comment by reidellawfirm** [comment]
Request to change the current text color (blue). I suffer from chromatic aberration and have a very difficult time seeing the color blue. My humble request is to chance the blue text color to another color.

**Comment by peepopoggers** [comment]
@reidellawfirm It could be a settings option stored in localstorage for that case, or you could try a css plugin to change all "a" elements to a different color.

**Comment by LukeSmithxyz** [comment]
I'm not tethered to the current colors, so I am open to changing it to something else someone suggests.

**Comment by LukeSmithxyz** [comment]
Changed the colors to be warmer, as in #221

**Comment by peepopoggers** [comment]
Hey @LukeSmithxyz I think the links would look better without the underlines. What do you think? Thanks.

**Comment by TheToyking10** [comment]
@LukeSmithxyz I agree with @peepopoggers . Perhaps a bit more spacing between the radio buttons or removing the underlines would be good as the list seems too cramped right now. Could also be the yellow.

Glad to hear you've switched to Hugo.

**Comment by isti03** [comment]
Removing link underlines in general [hurts accessibility](https://seirdy.one/2020/11/23/website-best-practices.html#in-defense-of-link-underlines), however it would definitely be more readable and it wouldn't be so much of an issue if it is only removed from the list. Adding more padding would make the site more usable for mobile users. Therefore, I would suggest something like:

```css
#artlist a, .tagcloud a {
	padding: 0.2em;
	display: inline-block;
	text-decoration: none;
}
```

**Comment by reidellawfirm** [comment]
> @reidellawfirm It could be a settings option stored in localstorage for that case, or you could try a css plugin to change all "a" elements to a different color.

Thanks for the suggestion, great idea to look into a css plugin.

**Comment by peepopoggers** [comment]
@isti03 I looked at the site you linked; for the bullet points, there are never links next to each other so it is fine.

**Comment by dynfactor** [comment]
I think that the website could done build using crystal, php or even nodejs and really not relaying on static html pages.
Yes its a great idea to generated them to static html.
But is it worth it? I don't think so, let the server generate it when it requested that it!
The recipes are very small as I can see and it would not take a lot of time to generated it live, right?
You can also cache the generated pages if you want to be more "economy".

**Comment by LukeSmithxyz** [comment]
> I think that the website could done build using crystal, php or even nodejs and really not relaying on static html pages. Yes its a great idea to generated them to static html. But is it worth it? I don't think so, let the server generate it when it requested that it! The recipes are very small as I can see and it would not take a lot of time to generated it live, right? You can also cache the generated pages if you want to be more "economy".

I can never tell if these people are kidding or not.

**Comment by peepopoggers** [comment]
php :skull:

**Comment by TheToyking10** [comment]
> I think that the website could done build using crystal, php or even nodejs and really not relaying on static html pages. Yes its a great idea to generated them to static html. But is it worth it? I don't think so, let the server generate it when it requested that it! The recipes are very small as I can see and it would not take a lot of time to generated it live, right? You can also cache the generated pages if you want to be more "economy".

Are you retarded?

**Comment by hsnenud** [comment]
Look @LukeSmithxyz, I understand and fully respect your desicion to not apply my idea (@dynfactor), but come on man are you gonna shut me up for that? (well it seems that you did, since i can't commented from my main account)

**Comment by hsnenud** [comment]
No, I am not kidding, what's wrong with nodejs, crystal or even php?
They are the "backend" so they don't run on the user's browser (so don't worry no javascript envolved here) and they are just designed for that thing.
I believe they are better if you want to add things and improve it with time than staticly generated site.
I don't mean adding javascript or bloat the site when I say "improve it", no it doesn't have to be like that.
I am just trying to sell this idea to you, you buy it or you don't it's up to you :)
Please don't take it personal, cause I didn't mean it :)

**Comment by hsnenud** [comment]
Even though, I can help even if I don't agree with you, so... would you unblock me @dynfactor so I can contribute? Thanks :)
