### ISSUE TITLE
To make based.cooking a sharable document

### ISSUE THREAD

**Issue by ermitxyz** [LukeSmithxyz/based.cooking#791]
With the simplicity of the syntax that hugo has, a easy script can transform any recipe to the LaTeX (or groff) syntax and then compile it to a PDF document.

With a shell script it can be auto-generated on the server each month with a corn job and the site can provide different versions for each lenguage (when hugo multilingual where actually implemented).

Benefits:
- Offline/local read mode: you can read based.cooking recepices without an internet connection.
- Less internet trafic: it may help with the bandwith of the server.
- Reach more people/normie friendly: at the start of the document can be a tutorial of "How to access the site and the updated recipes" so if your grandma receives the PDF via whatsapp, she can go too and enjoy the benefits of a search bar and the tags (like old magazines that came with a linux-cd did, just that's an URL).

Downsides:
- It's bloated (depends on the actual implementation though).
- If there's no good publicity on the first page about the URL and the newest recipes, less people will end up accessing the site.

Also, since the webpage is under CC, there's no problem with the license.

**Comment by ermitxyz** [comment]
If all end up working and the page gain popularity, a well compiled version of the document can be published on lindypress and the earning can be redirected to the maintenance of the server and domain name.

For some reason people love to help buying "merch" so it may work, but if the site shills a lot about the book on front-page, people may end up leaving the site : )

**Comment by LukeSmithxyz** [comment]
Interesting idea, but that's a long-term goal that I'm less interested in now.

If you can provide some immediately actionable way of converting markdown to tex, we can start there. But even that, I find is somewhat of an issue. There may also be some system for direct md -> pdf conversion. I'm not sure.

Either way, the easiest way to get printable documents is ctrl-p, which works fine now, although you're is welcome to open a PR about CSS for it if you want.

**Comment by explosion-mental** [comment]
yeah [pandoc](https://github.com/jgm/pandoc)
It is very interesting. I would say that if you want a pdf, u can easily wget and converted on your end. But it would be very nice to have at the end of some recipe a button/link to click and just download this as a pdf, mainly to share across (since for offline viewing, might as well download the webpage).
