### ISSUE TITLE
Styling on landing page - Underline overload

### ISSUE THREAD

**Issue by xargon666** [LukeSmithxyz/based.cooking#808]
I think all those underlines are a bit visually confusing, particularly in the categories section. I'm sure just setting underline to none would help.

Mainly wanted to post this because you cleared your issue tickets.

**Comment by LukeSmithxyz** [comment]
Yeah I'm going to push a change with this and some other stuff today. When the color scheme was different, underlined links were more needed because the colors were not as distinct as they are now.
