### ISSUE TITLE
Inherit the stylesheet of lugo

### ISSUE THREAD

**Issue by esdnm** [LukeSmithxyz/based.cooking#818]
based.cooking doesn't inherit the stylesheet of lugo. As a result not all recent modifications to lugo, such as [adding middle-dot via CSS](https://github.com/LukeSmithxyz/lugo/commit/0e34e523c6e9f2ab5c29c713863da3986769965d), are not available in based.cooking.

Either lugo's sytlesheet needs to be also included in based.cooking or changes to sytle.css made in lugo needs to be also added to bases.cooking's sytle.css

**Comment by LukeSmithxyz** [comment]
The middle dot thing has been reverted, so it's not an issue now. This will definitely not be necessary moving forward and I certainly would not want to make two calls to different CSS files without some principled reason.

**Comment by esdnm** [comment]
Let's see where https://github.com/gohugoio/hugo/issues/10070 goes
