### ISSUE TITLE
Add translations?

### ISSUE THREAD

**Issue by Naheel-Azawy** [LukeSmithxyz/based.cooking#82]
Hi, just a tiny suggestion. How about making it possible for people to add translations? Maybe for every `recipe.md` we have a `recipe.<language>.md` for each language? Or whatever structure that is more suitable.

This can add a lot of noise, of course, for English speaking users. I'm not sure if that would be considered bloated. But it would help much more people and make others contribute more, I guess.

And nice project btw, this is already so cool.

**Comment by LukeGoule** [comment]
Maybe a subdirectory instead so the main recipes list doesn't become highly cluttered, then a list of different languages in the index with urls to their respective directory. That could help the end user experience from being bloated I supposed.

**Comment by odnar-dev** [comment]
what about using subdomains and branches
every branche has a subdomain and dedicated to a language
en.based.cooking/carbonara.html > English > master branch
fr.based.cooking/carbonara.html > French > French branch
ar.based.cooking/carbonara.html > Arabic > Arabic branch....

**Comment by darltrash** [comment]
It would be super nice to create translations, i would love to make some in spanish :)

**Comment by LukeSmithxyz** [comment]
This is just way too much maintenance to keep up with. This thing has taken a lot of time just in English. Luckily, however, this is free software, so you can fork it and make your own equivalent site if you want.
