### ISSUE TITLE
Standardise units of measurement

### ISSUE THREAD

**Issue by vincent-uden** [LukeSmithxyz/based.cooking#822]
As it currently stands neither the formatting nor the actual units for the ingredients are consistent across the different recipes. For example [Glühwein](https://based.cooking/gluehwein/) is presented in metric units while [Swedish Pancakes](https://based.cooking/swedish-pancakes/) rather ironically is presented in imperial units.

I haven't used Hugo before so I'm unaware as to if it could handle the conversion between units. Otherwise my suggestions would be to add both units for all pages and require both sets of units for future additions.

Also I should mention that a potential response would be "just calculate the conversion while cooking" which I don't consider a reasonable response as finding the quantities of for the respective ingredients is exactly what a recipe is for.

**Comment by alexmo1997** [comment]
Excuse me, but how is this completed?
