### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jbonadiman** [LukeSmithxyz/based.cooking#951]
So... I'm guessing this project is abandoned/on-hold? Isn't there anyone else to approve the PRs?

**Comment by Spooghetti420** [comment]
Luke is probably in the forest or somewhere else, and if so could be back anywhere between 2 minutes and 2 years... Well, I hope he comes back or at least nominates someone to approve requests in hist stead, but for the time being we might just say that the most 'based' choice after all is to cut off your internet & read in a cabin or something. Sadly that doesn't fix our problem tho.

**Comment by jbonadiman** [comment]
We could also do this nomination, right?
Do we have contenders? Someone could create a fork and accept the PRs.

**Comment by jbonadiman** [comment]
Ok, I took matters with my own hands. What I did:

- I got the domain [libre.cooking](https://libre.cooking/).
- Forked the project and adapted it to be hosted in Vercel (free hosting and CI/CD is always nice).
- Changed the license to GPL instead of the "unlicensed" one.

This project is too good and too interesting to just get forgotten. I'm still waiting for the original owner to be active again, tho.
Meanwhile, I'll be accepting PRs and new maintainers in my [fork](https://github.com/jbonadiman/libre.cooking) (I accept all the help I could get - good-intentions people, please!).
Let's resurrect this project!

**Comment by Spooghetti420** [comment]
This is great, thanks for doing all of this. This project deserves to continue to be supported for everyone's benefit, so thanks again.

**Comment by simurgh9** [comment]
The fork seems to have lasted shorter than the original...

**Comment by jbonadiman** [comment]
There is yet another fork going on, I see no point on maintaining two.
And despite that, people are still opening PRs here... 🤡

I closed the other issue and I'll close this one too.
From my part, I got everything I needed, I don't see any point on keeping this open.

**Comment by simurgh9** [comment]
Could you link to the latest fork?

**Comment by ronaldl29** [comment]
@simurgh9 Here is mine. https://github.com/ronaldlong46/public-domain-recipes I've been bringing in the PRs from here
