### ISSUE TITLE
New fork

### ISSUE THREAD

**Issue by jbonadiman** [LukeSmithxyz/based.cooking#958]
This project doesn't have an update for a while and since we didn't have any reply from the original owner, I decided to create my own fork to keep his work alive. I truly believe this project is amazing and shouldn't be forgotten.

What I've done so far:
- I got the domain [libre.cooking](https://libre.cooking/).
- Forked the project and adapted it to be hosted in Vercel (free hosting and CI/CD is always nice).
- Changed the license to GPL instead of the "unlicensed" one.

I'll still wait for the original owner to return and to assign new maintainers, but in the meanwhile, I invite everyone here to check the [fork](https://github.com/jbonadiman/libre.cooking) and submit your PRs over there. I'll be accepting them following the same rules of here as best as I can.
I also invite people interested in keeping the project to be maintainers over there, so that this project doesn't risk dying again 😊.

**Comment by ronaldl29** [comment]
Let me know if there's any way I can help or if we can collaborate. I've also done something similar here:

https://github.com/ronaldlong46/public-domain-recipes
https://publicdomainrecipes.com/

I have began taking the forks made here and integrating them into the above repo.
